theme: jekyll-theme-minimal
title: creoii.dev
description: creoii portfolio
author: creoii
avatar: "/assets/img/icon.png"
social-network-links:
  email: "jackrzisa@gmail.com"
  github: jack-zisa
  linkedin: jack-zisa